Repository fs-04-Moving/4-Moving-Team1-BE, pull requests merged in 2025-04, with the labels that each got.

#24 [엄성민] 견적 생성 및 업데이트 api 구현
  src/controllers/auth.controller.ts
  src/controllers/estimate-request.controller.ts
  src/controllers/estimate.controller.ts
  src/controllers/profile.controller.ts
  src/controllers/user.controller.ts
  src/db/prisma/migrations/20250404064848_/migration.sql
  src/db/prisma/migrations/20250404072512_/migration.sql
  src/db/prisma/schema.prisma
  src/routes/estimate-request.router.ts
  src/routes/estimate.route.ts
  src/routes/index.ts
  src/routes/profile.route.ts
  src/routes/user.route.ts
  src/servieces/auth.service.ts
  src/servieces/estimate-request.sevice.ts
  src/servieces/estimate.service.ts
  src/servieces/profile.service.ts
  src/servieces/user.service.ts
  src/servieces/utills.ts
Labels: feat

#26 [엄성민] 에러처리 구문 수정
  src/controllers/estimate.controller.ts
  src/middleware/error.middleware.ts
Labels: fix

#27 [엄성민] 견적 요청 라우터 응답값 수정
  src/controllers/estimate-request.controller.ts
  src/controllers/estimate.controller.ts
  src/controllers/profile.controller.ts
  src/servieces/profile.service.ts
Labels: feat

#32 [엄성민] 찜하기 라우터 추가
  src/controllers/estimate-request.controller.ts
  src/controllers/estimate.controller.ts
  src/controllers/favorite.controller.ts
  src/db/prisma/migrations/20250407045731_/migration.sql
  src/db/prisma/migrations/20250407052650_/migration.sql
  src/db/prisma/migrations/20250407054558_/migration.sql
  src/db/prisma/schema.prisma
  src/routes/estimate.route.ts
  src/routes/favorite.route.ts
  src/routes/index.ts
  src/servieces/estimate.service.ts
  src/servieces/favorite.service.ts
  src/servieces/utills.ts
Labels: feat

#36 [엄성민] 프로필 변경시 토큰 재발급
  src/controllers/auth.controller.ts
  src/controllers/profile.controller.ts
  src/db/prisma/schema.prisma
  src/servieces/auth.service.ts
  src/servieces/profile.service.ts
Labels: feat

#40 [엄성민] 페이지네이션 기능 추가
  src/controllers/estimate-request.controller.ts
  src/controllers/estimate.controller.ts
  src/controllers/favorite.controller.ts
  src/controllers/profile.controller.ts
  src/controllers/review.controller.ts
  src/db/prisma/migrations/20250409051702_update_name/migration.sql
  src/routes/auth.route.ts
  src/routes/estimate-request.router.ts
  src/routes/estimate.route.ts
  src/routes/favorite.route.ts
  src/routes/profile.route.ts
  src/routes/review.route.ts
  src/routes/user.route.ts
  src/servieces/estimate-request.sevice.ts
  src/servieces/estimate.service.ts
  src/servieces/favorite.service.ts
  src/servieces/profile.service.ts
  src/servieces/review.serivce.ts
  src/servieces/utills.ts
  src/types/express.d.ts
  src/validations/auth.validation.ts
  src/validations/common.validation.ts
  src/validations/estimate-requset.validation.ts
  src/validations/profile.validation.ts
Labels: feat, refactor

#41 [엄성민] 상세페이지 리뷰보기 라우터 구현
  src/controllers/review.controller.ts
  src/routes/review.route.ts
  src/servieces/profile.service.ts
  src/servieces/review.serivce.ts
Labels: feat

#42 [엄성민] reafactoring : res 응답값 수정
  src/controllers/estimate.controller.ts
  src/controllers/favorite.controller.ts
  src/controllers/profile.controller.ts
  src/controllers/user.controller.ts
  src/db/prisma/migrations/20250410064034_add_notification/migration.sql
  src/db/prisma/schema.prisma
  src/servieces/estimate-request.sevice.ts
  src/servieces/profile.service.ts
  upload/profileImage-1744348645793.png
Labels: refactor

#44 fix: 라우터 수정, isFavorite 응답값 수정
  src/controllers/auth.controller.ts
  src/controllers/estimate-request.controller.ts
  src/controllers/estimate.controller.ts
  src/controllers/favorite.controller.ts
  src/controllers/profile.controller.ts
  src/controllers/review.controller.ts
  src/controllers/user.controller.ts
  src/db/prisma/migrations/20250414041619_add_has_request/migration.sql
  src/db/prisma/schema.prisma
  src/routes/auth/auth.route.ts
  src/routes/estimate-request/estimate-request.router.ts
  src/routes/estimate/estimate.route.ts
  src/routes/favorite/favorite.route.ts
  src/routes/index.ts
  src/routes/profile/profile.route.ts
  src/routes/review/review.route.ts
  src/routes/user/user.route.ts
  src/services/auth.service.ts
  src/services/estimate-request.sevice.ts
  src/services/estimate.service.ts
  src/services/favorite.service.ts
  src/services/profile.service.ts
  src/services/review.serivce.ts
  src/services/user.service.ts
  src/services/utills.ts
  src/validations/profile.validation.ts
Labels: feat, fix, perf, refactor

#45 [엄성민] 오류 메시지 추가/ 폴더 구조 변경
  src/routes/estimate-request/estimate-request.router.ts
  src/routes/estimate/customer/estimate.route.ts
  src/routes/estimate/estimate.route.ts
  src/routes/estimate/worker/estimate.route.ts
  src/routes/favorite/favorite.route.ts
  src/routes/user/user.route.ts
  src/services/auth.service.ts
  src/services/favorite.service.ts
  src/utils/scheduler.ts
Labels: chore, perf, refactor

#50 [조형민] refactor: 토큰 발급 로직 수정
  src/controllers/auth.controller.ts
  src/services/auth.service.ts
  src/types/auth.type.ts
  upload/profileImage-1743860629237.png
  upload/profileImage-1743860672627.png
  upload/profileImage-1743900217235.png
  upload/profileImage-1743904607088.png
  upload/profileImage-1743944486131.png
  upload/profileImage-1743944955887.png
  upload/profileImage-1743945152996.png
  upload/profileImage-1743945847259.png
  upload/profileImage-1743947362361.png
  upload/profileImage-1743947513037.png
  upload/profileImage-1743947763559.png
  upload/profileImage-1743947812946.png
  upload/profileImage-1743947914780.png
  upload/profileImage-1743948003314.png
  upload/profileImage-1743948401077.png
  upload/profileImage-1743949209592.png
  upload/profileImage-1744041700049.png
  upload/profileImage-1744041886033.png
  upload/profileImage-1744093149062.png
  upload/profileImage-1744176698738.png
  upload/profileImage-1744177056321.png
  upload/profileImage-1744177127816.png
  upload/profileImage-1744187545081.png
  upload/profileImage-1744189586128.png
  upload/profileImage-1744190292046.png
  upload/profileImage-1744190512245.png
  upload/profileImage-1744190565466.png
  upload/profileImage-1744190711508.png
  upload/profileImage-1744190805956.png
  upload/profileImage-1744190984716.png
  upload/profileImage-1744191349647.png
  upload/profileImage-1744239720693.png
  upload/profileImage-1744250359431.png
  upload/profileImage-1744250593294.png
  upload/profileImage-1744251231331.png
  upload/profileImage-1744251306009.png
  upload/profileImage-1744251372789.png
  upload/profileImage-1744251942458.png
  upload/profileImage-1744261423408.png
  upload/profileImage-1744679308896.png
  upload/profileImage-1744680011939.png
  upload/profileImage-1744681275084.png
  upload/profileImage-1744715231041.png
Labels: refactor

#51 [엄성민] 기사님 찾기 summary 추가, 프로필 응답 값 수정
  src/controllers/auth.controller.ts
  src/services/auth.service.ts
  src/services/profile.service.ts
  src/services/user.service.ts
  src/services/utills.ts
  src/types/auth.type.ts
Labels: feat, fix

#52 [엄성민] sse방식으로 알림 구현
  package-lock.json
  package.json
  src/app.ts
  src/controllers/estimate-request.controller.ts
  src/controllers/favorite.controller.ts
  src/controllers/notification.controller.ts
  src/db/prisma/migrations/20250418050213_add_notification_user_id/migration.sql
  src/db/prisma/migrations/20250418055159_/migration.sql
  src/db/prisma/schema.prisma
  src/middleware/auth.middleware.ts
  src/routes/index.ts
  src/routes/notification/notification.route.ts
  src/services/auth.service.ts
  src/services/estimate-request.sevice.ts
  src/services/estimate.service.ts
  src/services/notification.service.ts
  src/services/profile.service.ts
  src/services/user.service.ts
  src/services/utills.ts
Labels: chore, feat, refactor

#53 [엄성민] rafact: 코드 개선
  src/middleware/auth.middleware.ts
Labels: refactor

#55 [엄성민] 알림 구현
  src/controllers/estimate.controller.ts
  src/controllers/notification.controller.ts
  src/services/estimate.service.ts
  src/services/notification.service.ts
  src/services/profile.service.ts
Labels: chore, feat, fix

#65 [엄성민] ci:yml 파일 추가
  .github/workflows/deploy.yml
  src/app.ts
Labels: ci

#66 test: 자동화 작동되는지 테스트 커밋
  upload/profileImage-1743567427131.png
Labels: test
